services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: oauth_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
    command: start-dev --import-realm
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 90s

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: oauth-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/oauth_demo
      PORT: 3002
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    volumes:
      # Bind mount backend sources, but keep container's node_modules via anonymous volume
      - ./backend:/app/backend:delegated
      - /app/backend/node_modules
      # Mount prisma schema read-only
      - ./prisma:/app/prisma:ro

  app:
    build: .
    environment:
      PROVIDER_URL: http://localhost:8081
      REALM: demo
      ISSUER: http://localhost:8081/realms/demo
      CLIENT_ID: react-oauth
      REDIRECT_URI: http://localhost:3001
      SCOPE: "openid profile email"
      # Database connection for Prisma
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/oauth_demo"
    ports:
      - "3001:80"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

# Persistent volume for PostgreSQL data
volumes:
  postgres_data:
