services:
  postgres:
    restart: unless-stopped
    networks:
      - internal-net

  mongodb:
    restart: unless-stopped
    networks:
      - internal-net

  backend:
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      RUN_DEMO_PROJECT_SEED: ${RUN_DEMO_PROJECT_SEED:-false}
      RUN_DEMO_USERS_SEED: ${RUN_DEMO_USERS_SEED:-false}
      DEMO_PROJECT_MANAGER_EMAIL: ${DEMO_PROJECT_MANAGER_EMAIL:-}
      DEMO_PROJECT_MANAGER_SUB: ${DEMO_PROJECT_MANAGER_SUB:-}
    expose:
      - "3002"
    networks:
      - internal-net
      - host-proxy-net

  app:
    restart: unless-stopped
    environment:
      SHOW_ECCCH_DEBUG_OPERATIONS: ${SHOW_ECCCH_DEBUG_OPERATIONS:-false}
    expose:
      - "80"
    networks:
      - internal-net
      - host-proxy-net

networks:
  host-proxy-net:
    external: true
    name: host-proxy-net
  internal-net:
    driver: bridge
